spring:
  application:
    name: deliveryClientCart
  data:
    mongodb:
      uri: mongodb://localhost:27018/deliveryOrderClient
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/delivery
  server:
    port: 8085