server:
  port: 8086
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/delivery
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/delivery
            user-name-attribute: preferred_username
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: LxP7gsDnOKhpivvseAAFdDY0x546Ytvt
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: LxP7gsDnOKhpivvseAAFdDY0x546Ytvt