dreamer:
    delivery:
        service:
            uri: http://localhost:8081
            client-id: keycloak
server:
    port: 8080
spring:
  boot:
    admin:
      client:
        url: http://localhost:8086
        instance:
          name: Менеджерское приложение
          service-host-type: ip
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/delivery
      client:
          provider:
            keycloak:
                issuer-uri: http://localhost:8082/realms/delivery
                user-name-attribute: preferred_username
          registration:
              keycloak:
                  client-id: delivery-market
                  client-secret: Far30AtwzWsyZNebecuyqYZn8QlWcQAy
                  scope:
                    - openid
                    - view_catalogue
                    - edit_catalogue
                    - microprofile-jwt
              metrics:
                provider: keycloak
                client-id: delivery-market-metrics-client
                client-secret: fDCVjmif6Pcjjgm4UBFEPj1GBzvnGywW
                authorization-grant-type: client_credentials
                scope:
                  - metrics_server
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

