spring:
  application:
    name:deliveryFeedbackService
  data:
    mongodb:
      uri: mongodb://localhost:27017/deliveryFeedbackService
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/delivery
server:
  port: 8084

