spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalogue
    username: delivery
    password: delivery
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
server:
  port: 8081